#
# Makefile --
#
# (c) 2013 Prof Dr Andreas Mueller, Hochschule Rapeprswil
# $Id$
#
TEXFILES = genalg.tex simann.tex particles.tex antcolony.tex \
	simplex.tex blas.tex karmarkar.tex \
	descent.tex nlsimplex.tex \
	branchandbound.tex \
	brechung.tex

aufgaben.pdf:	aufgaben.tex $(TEXFILES)
	pdflatex aufgaben.tex
